### ISSUE TITLE
Add JSON report as a buffer accessible through the API

### ISSUE THREAD

**Issue by terrybr** [hasherezade/pe-sieve#105]
Hi,

It would be very useful if the scan results can be accessed through the API as a buffer. 

Thank you!
Terry

**Comment by hasherezade** [comment]
@terrybr I added a new API function: [PESieve_scan_ex](https://hasherezade.github.io/pe-sieve/pe__sieve__api_8h.html#a8e7c91bed131f09cd092769786290707) - please check it  out and let me know if this is what you expected.

For now it is just the scan report, but I will eventually combine the scan report and dump report in one (each in a separate section).

**Comment by f1-outsourcing** [comment]
@hasherezade 

Hi sorry for writing here. I am looking for some help with writing a sieve plugin. I was wondering if I could consult you for this by email or so.

**Comment by hasherezade** [comment]
hi @f1-outsourcing ! for now PE-sieve doesn't support plugins, but I may add it in the future. Feel free to create a topic in [discussions](https://github.com/hasherezade/pe-sieve/discussions), because this is some idea to brainstorm about. You can also send me an email to hasherezade-at-protonmail.com. The current issue is related to something else...

**Comment by terrybr** [comment]
@hasherezade The new API function works as expected!  Thank you so much!

**Comment by hasherezade** [comment]
@terrybr - the new function (with some improvements) is included in the official release [0.3.5](https://github.com/hasherezade/pe-sieve/releases/tag/v0.3.5) - please check it out!
